import Head from 'next/head'
import Image from 'next/image'

export default function Login() {
  return (
    <>
      <Head>
        <title>Car Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
<h1>5555</h1>
    </>
  )
}
